name: Build and Deploy ASP.NET Core App

on:
  push:
    branches:
      - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --no-restore -o publish

    - name: Create web.config
      run: |
        echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>" > publish/web.config
        echo "<configuration>" >> publish/web.config
        echo "  <location path=\".\" inheritInChildApplications=\"false\">" >> publish/web.config
        echo "    <system.webServer>" >> publish/web.config
        echo "      <handlers>" >> publish/web.config
        echo "        <add name=\"aspNetCore\" path=\"*\" verb=\"*\" modules=\"AspNetCoreModuleV2\" resourceType=\"Unspecified\" />" >> publish/web.config
        echo "      </handlers>" >> publish/web.config
        echo "      <aspNetCore processPath=\"dotnet\" arguments=\".\Tasks.dll\" stdoutLogEnabled=\"false\" stdoutLogFile=\".\logs\stdout\" hostingModel=\"inprocess\">" >> publish/web.config
        echo "        <environmentVariables>" >> publish/web.config
        echo "          <environmentVariable name=\"DB_CONNECTION_STRING\" value=\"${{ secrets.DB_CONNECTION_STRING }}\" />" >> publish/web.config
        echo "        </environmentVariables>" >> publish/web.config
        echo "      </aspNetCore>" >> publish/web.config
        echo "    </system.webServer>" >> publish/web.config
        echo "  </location>" >> publish/web.config
        echo "</configuration>" >> publish/web.config
        echo "<!--ProjectGuid: BB1997CA-7460-4A16-85A8-879E521560F7-->" >> publish/web.config

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: web-app
        path: |
          publish/web.config

    - name: Deploy to somee.com via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp
        local-dir: publish/
        server-dir: /www.tasks.somee.com/
